#!/usr/bin/env python3
#19500101 initial version daimon:/etc/Model/sh
import sys, os
from PIL import Image, ImageDraw, ImageFont
import magicbus, theride

magicbus_stops = [ 'Couzens/BSRB', 'Couzens/Zina Pitcher', 'BSRB']
theride_stops = ['1216', '1831']
stops_theride_rename = {'1216' : 'Couzens/BSRB', '1831' : 'BSRB' }
routes_theride_rename = {
	'4-TO BTC'			: '4-Y2A',
	'4-TO YTC'			: '4-A2Y',
	'32-TO MILLER P+R'	: '32',
	'91-TO CHELSEA'		: '91',
	'91-TO ANN ARBOR'	: '91',
	'92-TO CANTON'		: '92',
	'92-TO ANN ARBOR'	: '92',

}

def draw_png(stop_route_time, crop_spec):
	#
	width = 280
	height= 500
	row = 25
	#
	maze = (255, 209, 0)
	ross = (221, 202, 143)
	#
	fontsize = int(row/1.2)
	#
	bg = Image.open(f"{os.environ['DAISPLAY_VAR']}/background/background.png")
	img = bg.crop(crop_spec)
	draw = ImageDraw.Draw(img)
	fnt = ImageFont.truetype('/usr/share/fonts/TTF/DejaVuSans.ttf', fontsize)
	y = 0
	for st, route_time in sorted(stop_route_time.items()):
		draw.text((0, y), st, font=fnt, fill=maze)
		y += row
		for rt, time in sorted(route_time.items()):
			draw.text((20, y), rt, font=fnt, fill=ross)
			draw.text((100, y), time, font=fnt, fill=ross)
			y += row
	img.save('addon.png', 'PNG')
def merge_srt(srt1, srt2, stops_rename, routes_rename):
	for stop, route_time in srt2.items():
		stop_new = stops_rename.get(stop, stop)
		for route, time_list in route_time.items():
			route_new = routes_rename.get(route, route)
			new_time_list = srt1.setdefault(stop_new, {}).setdefault(route_new, []) 
			new_time_list += time_list
	return srt1

def main():
	try:
		stop_route_time = magicbus.get_stop_route_time(magicbus_stops)
	except:
		stop_route_time = {}
	try :
		theride_srt = theride.get_stop_route_time(theride_stops)
		stop_route_time = merge_srt(stop_route_time, theride_srt, stops_theride_rename, routes_theride_rename)
	except:
		pass
	#list to string
	for st, route_time in stop_route_time.items():
		for rt in route_time.keys():
			time_list = route_time[rt]
			time_list = list(set(time_list))
			route_time[rt] = ','.join([str(i) for i in sorted(time_list)])
	#
	crop_spec = tuple([int(s) for s in sys.argv[1].split('-')[1:5]])
	draw_png(stop_route_time, crop_spec)
	for st in sorted(stop_route_time.keys()):
		print(st)
		for route_time in sorted(stop_route_time.get(st, {}).items()):
			print(route_time)
if __name__ == '__main__': main()
