#!/usr/bin/env python3
#19500101 initial version daimon:/etc/Model/sh
import sys
import argparse
import json, urllib.request, os
from PIL import Image, ImageDraw, ImageFont

def main():
	key = os.environ.get('OPENWEATHERMAP_APPKEY')
	if key is None or key == '':
		degree, icon = '99', '01d'
	else:
		rtn = json.loads(urllib.request.urlopen(f'http://api.openweathermap.org/data/2.5/weather?id=4984247&APPID={key}').read().decode())
		degree, icon = round(1.8 * (rtn['main']['temp'] - 233.15) - 40), rtn['weather'][0]['icon']
	bg = Image.open(f"{os.environ['DAISPLAY_HOME']}/var/lib/daisplay/background/background.png")
	crop_spec = tuple([int(s) for s in sys.argv[1].split('-')[1:5]])
	img = bg.crop(crop_spec)
	draw = ImageDraw.Draw(img)
	fnt = ImageFont.truetype('/usr/share/fonts/TTF/DejaVuSans.ttf', 20)
	draw.text((10, 10), f'{degree}°', font=fnt, fill=(255,255,255))
	icon_img = Image.open(f"{os.environ['DAISPLAY_HOME']}/var/lib/daisplay/{sys.argv[1]}/icons/{icon}.png")
	img.paste(icon_img, (0, 20), icon_img)
	img.save('addon.png', 'PNG')
	print (degree, icon)
if __name__ == '__main__': main()
